In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Sure Screening for Edges in the Microbe-Microbe Interaction Network
1. Spearman
2. SparCC (T2D)
3. CLR + rmcorr (T2D)

# SparCC on PCOS

In [2]:
pcos = pd.read_csv("../data/clean.csv")
pcos

,group,Acetatifactor,Acinetobacter,Aeromicrobium,Aureibacillus,Beggiatoa,Breznakibacter,Catenococcus,Clostridia_vadinBB60_group,Coprococcus,...,Rikenellaceae_RC9_gut_group,Ruminococcus,Schleiferia,Slackia,Steroidobacter,Thauera,Truepera,Tyzzerella,UCG-002,UCG-005
0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.045935,0.529459,...,0.0,6.839446,0.0,0.000000,0.0,0.0,0.0,0.140222,3.503131,0.834079
1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.043520,0.947776,...,0.0,3.428433,0.0,0.000000,0.0,0.0,0.0,0.000000,2.961799,0.041103
2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.399365,...,0.0,4.470259,0.0,0.005830,0.0,0.0,0.0,0.000000,0.918247,0.033523
3,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.041250,...,0.0,7.956611,0.0,0.087083,0.0,0.0,0.0,0.516385,0.863188,0.200137
4,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.007486,1.689375,...,0.0,1.085492,0.0,0.000000,0.0,0.0,0.0,0.000000,2.450467,1.766732
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.363798,...,0.0,1.467568,0.0,0.000000,0.0,0.0,0.0,0.000000,0.267280,0.009899
944,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.169985,...,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.050800,0.000000,0.000000
945,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.763001,...,0.0,0.244190,0.0,0.000000,0.0,0.0,0.0,0.000000,0.966028,0.037568
946,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.022016,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000
947,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.383767,...,0.0,1.212703,0.0,0.000000,0.0,0.0,0.0,0.000000,0.846206,0.285906

In [10]:
pcos_hc = pcos[pcos['group'] == 0].drop(columns = ['group'])
pcos_hc.T.to_csv("../data/hc.csv")

In [20]:
pcos_pcos = pcos[pcos['group'] == 1].drop(columns = ['group'])
pcos_pcos.T.to_csv("../data/pcos.csv")

In [40]:
def get_significant_cor_pairs(sparcc_fp, sparcc_pval_fp):
    sparcc = pd.read_csv(sparcc_fp)
    sparcc = sparcc.iloc[:, 1:]
    sparcc.columns = pcos_hc.columns

    sparcc_pval = pd.read_csv(sparcc_pval_fp)
    sparcc_pval = sparcc_pval.iloc[:, 1:]
    sparcc_pval.columns = pcos_hc.columns

    sparcc_genus_A, sparcc_genus_B, sparcc_rho, sparcc_p = [], [], [], []
    
    for i in range(sparcc_pval.shape[1]):
        for j in range(i, sparcc_pval.shape[1]):
            if sparcc_pval.iloc[i, j] <= 0.05:
                sparcc_genus_A.append(sparcc_pval.columns[i])
                sparcc_genus_B.append(sparcc_pval.columns[j])
                sparcc_rho.append(sparcc.iloc[i, j])
                sparcc_p.append(sparcc_pval.iloc[i, j])

    sparcc_sig = pd.DataFrame(data = {'genus_A': sparcc_genus_A,
                                      'genus_B': sparcc_genus_B,
                                      'rho': sparcc_rho,
                                      'p': sparcc_p})
    return sparcc_sig

In [41]:
get_significant_cor_pairs("../../hc_sparcc.csv", "../../hc_pvals_one_sided.csv")

            genus_A           genus_B       rho     p
0     Acetatifactor         Beggiatoa -0.022652  0.03
1     Acetatifactor   Corynebacterium  0.023628  0.05
2     Acetatifactor             Dorea -0.028981  0.03
3     Acetatifactor  Faecalibacterium -0.052118  0.00
4     Acetatifactor        Kineothrix  0.058560  0.00
..              ...               ...       ...   ...
136    Ruminococcus           UCG-002  0.070926  0.00
137    Ruminococcus           UCG-005  0.069220  0.00
138  Steroidobacter        Tyzzerella  0.026290  0.02
139         Thauera           UCG-002 -0.027440  0.01
140         UCG-002           UCG-005  0.170823  0.00

[141 rows x 4 columns]

In [42]:
get_significant_cor_pairs("../../pcos_sparcc.csv", "../../pcos_pvals_one_sided.csv")

           genus_A        genus_B       rho     p
0    Acetatifactor     Dubosiella -0.031538  0.01
1    Acetatifactor        Slackia  0.021806  0.04
2    Acinetobacter  Aeromicrobium  0.075095  0.00
3    Acinetobacter      Beggiatoa  0.027421  0.01
4    Acinetobacter    Coprococcus -0.028776  0.01
..             ...            ...       ...   ...
154   Ruminococcus        UCG-005  0.025481  0.01
155        Slackia        UCG-005 -0.026026  0.04
156     Tyzzerella        UCG-002 -0.022050  0.02
157     Tyzzerella        UCG-005 -0.037654  0.01
158        UCG-002        UCG-005  0.105338  0.00

[159 rows x 4 columns]